import Head from 'next/head'
import Mensagem from '@/components/Mensagem';
import React, { useEffect, useState } from 'react';
import { db } from '../utils/firebase';
import { collection, query, orderBy, onSnapshot } from 'firebase/firestore';
import Link from 'next/link';

export default function Home() {

    const [todasPostagens, setTodasPostagens] = useState([]);

    const getPostagens = async () => {
        const postagens = collection(db, 'postagens');
        const q = query(collection(db, 'postagens'), orderBy('data', 'desc'));
        const unsubscribe = onSnapshot(q, (querySnapshot) => {
            setTodasPostagens(querySnapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
        });
        return unsubscribe;
    }

    useEffect(() => {
        getPostagens();
    }, []);

    return (
        <>
            <Head>
                <title>Social Spot</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div
                className='flex flex-col items-center justify-center py-2'
            >
                <h2 className='text-2xl font-bold text-gray-900'>As pessoas estão falando sobre isso</h2>
                {
                    todasPostagens.map(postagem => (
                        <Mensagem
                            key={postagem.id}
                            id={postagem.id}
                            texto={postagem.texto}
                            imagem={postagem.imagem}
                            data={postagem.data}
                            usuario={postagem.usuario}
                            fotoUsuario={postagem.fotoUsuario}
                        >
                            <Link
                                href={{pathname: `/${postagem.id}`, query: {...postagem} }}
                            >
                                <button
                                    className='px-4 py-2 text-black border-2 border-black rounded-md hover:scale-75 transition-all duration-300 my-3'
                                >{postagem.comentarios?.length} comentarios</button>
                            </Link>
                        </Mensagem>
                    ))
                }
            </div>
        </>
    )
}
